### PR TITLE
Added ifft

### PR DESCRIPTION
**Pull request by MaximilianBuegler**
Just added ifft and therefore allowed complex input in your fft code.

### CODE REVIEW

**Comment by waxspin** [comment]
@homernl82 Thanks for this!  We are happy to include it, but would you mind just adding some markdown to the README.md file to illustrate an example of using the ifft as you intended?  If this is not something you will have time to do, let me know and I can add it at some point, just won't have time immediately.

**Comment by homernl82** [comment]
Here you go...

**Comment by MaximilianBuegler** [comment]
I also added tests to test.js and their results to the readme, also incremented the version number. Should all be perfect now.

**Comment by waxspin** [comment]
Awesome, thanks! I'll check this out and merge in as soon as I'm back at my
computer.

**Comment by sylarcp** [comment]
@waxspin  Well, off the topic a little bit. Since both the input and output are a series of points. Given the time step is 1ms in time domain,  do you know how to tell the frequency step for the plots in frequency domain?   Thanks.

**Comment by waxspin** [comment]
@sylarcp To answer your question, the frequency step can be calculated as Fs (sampling frequency) divided by N (number of points in the FFT size).   A much more detailed explanation can be found [here](http://stackoverflow.com/questions/4364823/how-do-i-obtain-the-frequencies-of-each-value-in-an-fft/4371627#4371627) and a more full explanation about the mathematics behind the DFT (very dense though) can be found [here.](https://en.wikipedia.org/wiki/Discrete_Fourier_transform)

**Comment by sylarcp** [comment]
@waxspin Thanks! This answers my question.

**Pull request merged**
